# Generated by Django 5.0.6 on 2024-06-29 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=40)),
                ('apellidoPaterno', models.CharField(max_length=25)),
                ('apellidoMaterno', models.CharField(max_length=25)),
                ('correo', models.CharField(max_length=50, unique=True)),
                ('usuario', models.CharField(max_length=20)),
                ('contraseña', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
