# Generated by Django 5.0.6 on 2024-06-30 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_cliente_delete_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='apellidoMaterno',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='apellidoPaterno',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='nombres',
        ),
        migrations.AddField(
            model_name='cliente',
            name='apellido_materno',
            field=models.CharField(default='ApellidoMaterno', max_length=50),
        ),
        migrations.AddField(
            model_name='cliente',
            name='apellido_paterno',
            field=models.CharField(default='ApellidoPaterno', max_length=50),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(default='Nombre', max_length=50),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='correo',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
